stages:
  - build
  - upload
  - release

build-plugin:
  stage: build
  rules:
    - if: $CI_COMMIT_TAG
  image: docker
  services:
    - docker:dind
  tags:
    - real-dind
  before_script:
    - apk add --no-cache go make
  script:
    - make download-tools
    - make build
  artifacts:
    when: on_success
    expire_in: 1 day
    paths:
      - build

push-plugin:
  stage: upload
  rules:
    - if: $CI_COMMIT_TAG
  needs:
    - job: build-plugin
      artifacts: true
  image: curlimages/curl
  script:
    - 'export GO_VERS=$(cat build/gotify-server-go-version)'
    - 'echo "GO_VERS=$GO_VERS" > variables.env'
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file build/gotify-webhooks-linux-amd64.so "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/gotify-webhooks/${CI_COMMIT_TAG}_go${GO_VERS}/gotify-webhooks-linux-amd64.so"'
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file build/gotify-webhooks-linux-arm-7.so "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/gotify-webhooks/${CI_COMMIT_TAG}_go${GO_VERS}/gotify-webhooks-linux-arm-7.so"'
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file build/gotify-webhooks-linux-arm64.so "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/gotify-webhooks/${CI_COMMIT_TAG}_go${GO_VERS}/gotify-webhooks-linux-arm64.so"'
  artifacts:
    reports:
      dotenv: variables.env

release-plugin:
  stage: release
  rules:
    - if: $CI_COMMIT_TAG
  needs:
    - job: push-plugin
      artifacts: true
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  script:
    - 'echo "Releasing ${CI_COMMIT_TAG}_go${GO_VERS}"'
  release:
    name: "Release ${CI_COMMIT_TAG}_go${GO_VERS}"
    description: "Release for version ${CI_COMMIT_TAG}_go${GO_VERS} for the Gotify Webhooks Plugin, compatible with all version of Gotify built with Go ${GO_VERS}"
    tag_name: "$CI_COMMIT_TAG"
    assets:
      links:
        - name: gotify-webhooks-linux-amd64.so
          url: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/gotify-webhooks/${CI_COMMIT_TAG}_go${GO_VERS}/gotify-webhooks-linux-amd64.so"
          link_type: package
        - name: gotify-webhooks-linux-arm-7.so
          url: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/gotify-webhooks/${CI_COMMIT_TAG}_go${GO_VERS}/gotify-webhooks-linux-arm-7.so"
          link_type: package
        - name: gotify-webhooks-linux-arm64.so
          url: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/gotify-webhooks/${CI_COMMIT_TAG}_go${GO_VERS}/gotify-webhooks-linux-arm64.so"
          link_type: package
