on:
  push:

jobs:
  build-and-push-plugin:
    runs-on: docker
    container:
      # We need to use docker:dind directly instead of via `services`
      # since the Gotify Makefile uses `docker run` with volume mounts.
      # Mounting them to the dind service is not only hacky, but also
      # volume mounts are forbidden by the runner. 
      image: docker:dind
      options: --privileged
    env:
      DOCKER_HOST: unix:///var/lib/docker.sock
    steps:
      - name: Install dependencies
        run: apk add --no-cache bash git nodejs jq make go curl
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Start Docker daemon
        run: |
          dockerd-entrypoint.sh &
          
          for i in {1..30}; do
            if docker info >/dev/null 2>&1; then
              echo "Docker daemon ready"
              break
            fi
            echo "Waiting $i/30"
            sleep 2
          done
          
          # Check
          docker info
      - name: Download tools
        run: make download-tools GOTIFY_VERSION=v2.9.1
      - name: Build
        run: |
          make build GOTIFY_VERSION=v2.9.1
      - name: Upload all
        run: |
          curl --user ${{ forgejo.actor }}:${{ secrets.REGISTRY_TOKEN }} --upload-file build/${{ inputs.package-name }}-linux-amd64.so \
            ${{ forgejo.server_url }}/api/packages/${{ forgejo.repository_owner }}/generic/${{ inputs.package-name }}/${{ inputs.target-tag }}-gotify_${{ inputs.gotify-version }}-go_${{ inputs.go-version }}/${{ inputs.package-name }}-linux-amd64.so
          curl --user ${{ forgejo.actor }}:${{ secrets.REGISTRY_TOKEN }} --upload-file build/${{ inputs.package-name }}-linux-arm-7.so \
            ${{ forgejo.server_url }}/api/packages/${{ forgejo.repository_owner }}/generic/${{ inputs.package-name }}/${{ inputs.target-tag }}-gotify_${{ inputs.gotify-version }}-go_${{ inputs.go-version }}/${{ inputs.package-name }}-linux-arm-7.so
          curl --user ${{ forgejo.actor }}:${{ secrets.REGISTRY_TOKEN }} --upload-file build/${{ inputs.package-name }}-linux-arm64.so \
            ${{ forgejo.server_url }}/api/packages/${{ forgejo.repository_owner }}/generic/${{ inputs.package-name }}/${{ inputs.target-tag }}-gotify_${{ inputs.gotify-version }}-go_${{ inputs.go-version }}/${{ inputs.package-name }}-linux-arm64.so
